# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSMClientToolsSetup

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Software Trust Manager client tools
        id: STMClientToolsSetup
        run: |
          npm ci
          npm i --save-dev @types/proper-lockfile
          npm run build
          npm  start

      - name: Verify installation
        run: |
          echo "The PKCS11 is installed at ${{steps.STMClientToolsSetup.outputs.PKCS11_CONFIG}}"
          cd "${{ steps.STMClientToolsSetup.outputs.extractPath }}"
          echo "Tools installed are ..."
          ls

    env:
      SSM_CLIENT_INSTALLER_READ_TOKEN: ${{ secrets.SSM_CLIENT_INSTALLER_READ_TOKEN }}
      FORCE_DOWNLOAD_TOOLS: true

