# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSMClientToolsSetup

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Secure Software Manager client tools
        id: SSMClientToolsSetup
        run: |
          npm ci
          npm run build
          npm  start
      - run: smctl -v  
      - if: matrix.os=='windows-latest'   
        run: | 
          smctl windows ksp list
          smctl sign
          apksigner version
          jarsigner --help
          nuget --help
          mage --help
        shell: cmd  
        
      - name: Verify installation
        run: |
          echo "The PKCS11 is installed at ${{steps.SSMClientToolsSetup.outputs.PKCS11_CONFIG}}"
          cd "${{ steps.SSMClientToolsSetup.outputs.extractPath }}"
          echo "Tools installed are ..."
          dir
    env:
      SSM_CLIENT_INSTALLER_READ_TOKEN: ${{ secrets.SSM_CLIENT_INSTALLER_READ_TOKEN }}
